sonar.projectKey=qualitytrack-frontend
sonar.projectName=qualitytrack-frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=dist/**
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
